apiVersion: v1
kind: Service
metadata:
  name: foxglove-service
spec:
  type: NodePort
  selector:
    app: fusion-bot
  ports:
    - protocol: TCP
      port: 8765
      targetPort: 8765
      nodePort: 30005
