apiVersion: apps/v1
kind: Deployment
metadata:
  name: fusion-bot-simulation
  labels:
    app: fusion-bot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fusion-bot
  template:
    metadata:
      labels:
        app: fusion-bot
    spec:
      containers:
      - name: fusion-bot-container
        image: fusion_bot:latest
        imagePullPolicy: IfNotPresent
        # We must allow the container to use its own DDS network internally
        env:
        - name: ROS_DOMAIN_ID
          value: "0"
        ports:
        - containerPort: 8765
          name: foxglove-ws
        resources:
          requests:
            memory: "2Gi"
            cpu: "1000m"
          limits:
            memory: "4Gi"
            cpu: "2000m"
